# Generated by Django 4.2 on 2024-01-23 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stockdata", "0002_balancesheet_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="balancesheet",
            old_name="good_will",
            new_name="goodwill",
        ),
        migrations.RenameField(
            model_name="balancesheet",
            old_name="non_currrent_assets_other",
            new_name="non_current_assets_other",
        ),
    ]
