# Generated by Django 4.1.13 on 2024-01-23 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stockdata", "0003_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="General",
        ),
    ]
