# Generated by Django 4.1.13 on 2024-01-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stockdata", "0004_delete_general"),
    ]

    operations = [
        migrations.CreateModel(
            name="General",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("type", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=200)),
                ("exchange", models.CharField(max_length=50)),
                ("currency_code", models.CharField(max_length=10)),
                ("currency_name", models.CharField(max_length=50)),
                ("currency_symbol", models.CharField(max_length=10)),
                ("country_name", models.CharField(max_length=100)),
                ("country_iso", models.CharField(max_length=10)),
                ("isin", models.CharField(max_length=20)),
                ("primary_ticker", models.CharField(max_length=20)),
                ("cusip", models.CharField(max_length=20)),
                ("fiscal_year_end", models.CharField(max_length=50)),
                ("sector", models.CharField(max_length=100)),
                ("industry", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("address", models.TextField()),
                ("phone", models.CharField(max_length=50)),
                ("web_url", models.URLField()),
                ("logo_url", models.URLField()),
                ("full_time_employees", models.IntegerField()),
                ("updated_at", models.DateField()),
            ],
        ),
    ]
