# Generated by Django 4.1.13 on 2024-01-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stockdata", "0005_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="general",
            name="cusip",
        ),
        migrations.AlterField(
            model_name="general",
            name="full_time_employees",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
