# Generated by Django 4.1.13 on 2024-01-23 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stockdata", "0009_remove_general_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Highlights",
            fields=[
                (
                    "general",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="highlights",
                        serialize=False,
                        to="stockdata.general",
                    ),
                ),
                (
                    "market_capitalization",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("ebitda", models.DecimalField(decimal_places=2, max_digits=15)),
                ("pe_ratio", models.DecimalField(decimal_places=4, max_digits=10)),
                ("peg_ratio", models.DecimalField(decimal_places=4, max_digits=10)),
                (
                    "wall_street_target_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("book_value", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "dividend_share",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "dividend_yield",
                    models.DecimalField(decimal_places=4, max_digits=10),
                ),
                (
                    "earnings_share",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "eps_estimate_current_year",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "eps_estimate_next_year",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "eps_estimate_next_quarter",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "eps_estimate_current_quarter",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("most_recent_quarter", models.DateField()),
                ("profit_margin", models.DecimalField(decimal_places=4, max_digits=10)),
                (
                    "operating_margin_ttm",
                    models.DecimalField(decimal_places=4, max_digits=10),
                ),
                (
                    "return_on_assets_ttm",
                    models.DecimalField(decimal_places=4, max_digits=10),
                ),
                (
                    "return_on_equity_ttm",
                    models.DecimalField(decimal_places=4, max_digits=10),
                ),
                ("revenue_ttm", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "revenue_per_share_ttm",
                    models.DecimalField(decimal_places=4, max_digits=10),
                ),
                (
                    "quarterly_revenue_growth_yoy",
                    models.DecimalField(decimal_places=4, max_digits=10),
                ),
                (
                    "gross_profit_ttm",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "diluted_eps_ttm",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "quarterly_earnings_growth_yoy",
                    models.DecimalField(decimal_places=4, max_digits=10),
                ),
            ],
        ),
    ]
