# Generated by Django 4.1.13 on 2024-01-23 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stockdata", "0012_technicals"),
    ]

    operations = [
        migrations.CreateModel(
            name="SplitsDividends",
            fields=[
                (
                    "general",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="splits_dividends",
                        serialize=False,
                        to="stockdata.general",
                    ),
                ),
                (
                    "forward_annual_dividend_rate",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "forward_annual_dividend_yield",
                    models.DecimalField(decimal_places=4, max_digits=5),
                ),
                ("payout_ratio", models.DecimalField(decimal_places=4, max_digits=10)),
                ("dividend_date", models.DateField()),
                ("ex_dividend_date", models.DateField()),
                ("last_split_factor", models.CharField(max_length=20)),
                ("last_split_date", models.DateField()),
            ],
        ),
    ]
