# Generated by Django 4.1.13 on 2024-01-23 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stockdata", "0013_splitsdividends"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalystRatings",
            fields=[
                (
                    "general",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="analyst_ratings",
                        serialize=False,
                        to="stockdata.general",
                    ),
                ),
                ("rating", models.DecimalField(decimal_places=4, max_digits=5)),
                ("target_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("strong_buy", models.IntegerField()),
                ("buy", models.IntegerField()),
                ("hold", models.IntegerField()),
                ("sell", models.IntegerField()),
                ("strong_sell", models.IntegerField()),
            ],
        ),
    ]
