# Generated by Django 4.1.13 on 2024-01-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stockdata", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="balancesheet",
            name="type",
            field=models.CharField(
                choices=[("yearly", "Yearly"), ("quarterly", "Quarterly")],
                default="yearly",
                max_length=10,
            ),
        ),
    ]
