# Generated by Django 4.1.13 on 2024-01-30 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockdata', '0005_incomestatement'),
    ]

    operations = [
        migrations.CreateModel(
            name='CAGR',
            fields=[
                ('general', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='general_cagr', serialize=False, to='stockdata.general')),
                ('total_revenue_cagr', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('gross_profit_cagr', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('net_income_cagr', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
            ],
        ),
    ]
