const API_URL = process.env.REACT_APP_API_URL;
const API_KEY = process.env.REACT_APP_API_KEY;
const AUTHORIZATION_TOKEN = process.env.REACT_APP_AUTHORIZATION_TOKEN;

export { API_URL, API_KEY, AUTHORIZATION_TOKEN };
